services:
    app.ldap.client:
        class: Symfony\Component\Ldap\Ldap
        public: true
        arguments:
            - '@app.ldap.adapter'

    app.ldap.adapter:
        class: Symfony\Component\Ldap\Adapter\ExtLdap\Adapter
        arguments:
            - host: '%ldap_host%'
            - port: 389

    AppBundle\Ldap\LdapUserProvider:
        arguments:
            - '@app.ldap.client'
            - '%ldap_pwd%'

#    app.ldap_authenticator:
#        class: AppBundle\Security\LdapGuardAuthenticator
#        arguments:
#            - '@session'

    app.ldap.provider:
        class: Symfony\Component\Security\Core\User\LdapUserProvider
        arguments:
            - '@app.ldap.client'
            - '%ldap_base_dn%'
            - '%ldap_search_dn%'
            - '%ldap_pwd%'
            - roles:
                - 'ROLE_EMPLOYE'
            - 'uid'
