security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            encode_as_base64: false
            iterations: 10
        AppBundle\Entity\User: plaintext

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login_ldap:
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'uid={username},dc=example,dc=com'
                check_path: /oauth/v2/auth/ldap_login_check

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value
        admin:
            pattern: ^/admin
            http_basic:
                realm: 'Please administrator, identify yourself'
                provider: in_memory
    providers:
        in_memory:
            memory:
                users:
                    oauthserver:
                        password: %admin_password%
                        roles: 'ROLE_ADMIN'
        ldap_biig:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: dc=example,dc=com
                search_dn: "cn=read-only-admin,dc=example,dc=com"
                search_password: password
                default_roles: ROLE_EMPLOYE
                uid_key: uid

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }