version: '2'

services:
    # PHP
    phpfpm:
      restart: always
      extends:
        file: php-fpm-7.yml
        service: phpfpm
    #  links:
    #    - db:db

    # NGINX
    nginx:
      restart: always
      image: nginx
      ports:
        - "8000:80"
      links:
        - phpfpm:phpfpm
      volumes:
        - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        - ./symfony:/var/www/html
        - ./log/nginx:/var/log/nginx

