version: '2'

services:
    # PHP
    phpfpm:
      restart: always
      env_file:
        - .env
      extends:
        file: php-fpm-7.yml
        service: phpfpm

    # NGINX
    nginx:
      restart: always
      image: nginx:1.13.6
      ports:
        - "8001:80"
      links:
        - phpfpm:phpfpm
      volumes:
        - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www/html
        - ./log/nginx:/var/log/nginx

    # MYSQL
    db:
      restart: always
      image: mariadb:10.2.10
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 0qXW4FdDlTJQ0MN6xIv70Pfk
        MYSQL_USER: oauth_train
        MYSQL_PASSWORD: 0LuV75nG2GZA7fLDb7f
        MYSQL_DATABASE: oauth_train

    #PHPMYADMIN
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 7001:80
        environment:
            MYSQL_ROOT_PASSWORD: 0qXW4FdDlTJQ0MN6xIv70Pfk
            MYSQL_USER: oauth_train
            MYSQL_PASSWORD: 0LuV75nG2GZA7fLDb7f
            MYSQL_DATABASE: oauth_train
        depends_on:
            - db

